menu:
  Home: /
  
menu_external:
  Github: https://github.com/bullluo23

widgets: 
- search
- category
- tag

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: false
  twitter: false
  google: false
  pinterest: false

fancybox: true

google_analytics:
rss: